services:
  satellite:
    image: lunyaadev/rhasspy-wyoming-satellite
    container_name: wyoming-satellite
    restart: unless-stopped
    ports:
      - "10700:10700"
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    command:
      [
        "--name", "my satellite",
        "--uri", "tcp://0.0.0.0:10700",
        "--mic-command", "arecord -D plughw:4,0 -r 16000 -c 1 -f S16_LE -t raw",
        "--snd-command", "aplay -D plughw:4,0 -r 22050 -c 1 -f S16_LE -t raw",
        "--mic-auto-gain", "5",
        "--mic-noise-suppression", "2",
        "--awake-wav", "./sounds/awake.wav",
        "--done-wav", "./sounds/done.wav",
        "--timer-finished-wav", "./sounds/timer_finished.wav",
        "--debug",
      ]