name: Build Docker Image

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'main'

jobs:
  check-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get latest release tag
        id: get_release
        run: |
          curl -s https://api.github.com/repos/rhasspy/wyoming-satellite/releases/latest \
            | jq -r '.tag_name' > version.txt
          echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT

      - name: Check if image already exists
        run: |
          if docker manifest inspect lunyaadev/rhasspy-wyoming-satellite:$(cat version.txt) > /dev/null 2>&1; then
            echo "Image already exists. Skipping."
            exit 0
          fi

      - name: Download release tarball
        run: |
          curl -L -o release.tar.gz \
            https://github.com/rhasspy/wyoming-satellite/archive/refs/tags/$(cat version.txt).tar.gz
          mkdir source && tar -xzf release.tar.gz -C source --strip-components=1

      - name: Add custom Dockerfile
        run: |
          cp ./Dockerfile ./source/

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./source
          push: true
          tags: |
            lunyaadev/rhasspy-wyoming-satellite:${{ steps.get_release.outputs.version }}
            lunyaadev/rhasspy-wyoming-satellite:latest
